### ISSUE TITLE
Settings: Jira URL doesn't accept context path

### ISSUE THREAD

**Issue by creinig** [Chariyski/JIRA-Cards-for-Task-Board#10]
When trying to enter the Jira URL, it is marked as invalid as soon as something other than "https://HOSTNAME" is entered. In our (company) case jira is installed as "https://HOSTNAME/jira", so the plugin apparently cannot be configured to access jira at all.

The cause seems to be the regex in app/index.html, line 369. Probably it would be fine to append
`(/\w+)*/?` to allow for any number of path parts. Or just `(/\w+)`  for a single context path (should cover 99% of all cases)

Plugin version: 2.0.2

Update 2015-11-19: formatting fix

**Comment by Chariyski** [comment]
Hi @creinig,

sorry for the late response. Your request will be available in v.2.0.4

**Comment by Chariyski** [comment]
@creinig The new version is available and you should have the update in the next 24h.
