### ISSUE TITLE
Base url not accepting unusual top domains

### ISSUE THREAD

**Issue by danielalbinsson** [Chariyski/JIRA-Cards-for-Task-Board#11]
Our jira installation is located on a url that is not ending .com and it seams that is the extension can will not validate the base url. Our url is ending .global

![image](https://cloud.githubusercontent.com/assets/1328755/11185239/2b19ee14-8c7c-11e5-8897-013848b5fb86.png)

Thanks

**Comment by danielalbinsson** [comment]
Thanks! Worke great now!

**Comment by Chariyski** [comment]
Thanks for the feedback.
