### ISSUE TITLE
Feature Request - add color indication

### ISSUE THREAD

**Issue by thim81** [Chariyski/JIRA-Cards-for-Task-Board#12]
Hi Krasimir,

I love your Chrome extension.
It is a feature I missed while using Jira and your add-on is so simple to use and yet so darn handy.

I would like to add a feature to add some colors based on the types or 
That way it's visually more distinct on the board.

I tried to run the project locally but I was not able to run it properly due to javascript that complaints about 

```
this.$['dialog-popup'].open();
```

So I think, something is run with my bower install and or gulp.

Regards,
Tim

**Comment by Chariyski** [comment]
HI Tim,

I found that the bower can't install the version of the polymer that was used.
I've updated the version to 1.2.0 and it is working again.

Now it should be fine for contribution :)

Best regards,
Krasimir

**Comment by thim81** [comment]
Hi Krasimir,

Thanks for the input and update of the readme with the setup steps.
With your latest changes the plugin is working perfect.

Regards,
Tim
