### ISSUE TITLE
Documentation request - Clean-up setup

### ISSUE THREAD

**Issue by thim81** [Chariyski/JIRA-Cards-for-Task-Board#13]
Hi Krasimir,

If possible, could you write a short how-to to setup the project locally from scratch.

Regards,
Tim

**Comment by Chariyski** [comment]
Hi Tim,

I've added ["How to setup"](https://github.com/Chariyski/JIRA-Cards-for-Task-Board/blob/master/README.md#how-to-setup) to the README.md file.

Regards,
Krasimir
