### ISSUE TITLE
Add a new template

### ISSUE THREAD

**Issue by abrylov** [Chariyski/JIRA-Cards-for-Task-Board#4]
Hello Krasimir, 

I want to say thank you for the lovely extension :) And wanted to ask you, is it possible to add a new template with some additional values: 
 - Estimation (in hours for tasks and in story points for user stories)
 - Description
 - Type of issue (UserStory\Subtask)

Thanks in advance.

**Comment by Chariyski** [comment]
Hello abrylov ,

I'm glad that you like the extension :).
I can easily add a new template, but can you give me some mockup, or the design is up to me?

Best regards,
Krasimir

**Comment by abrylov** [comment]
Hey Krasimir.

It would be nice to have something like this
[image: Встроенное изображение 1]

We actually print task stories a little smaller to differentiate them from
user stories on the board, but I'm not sure that you could do it.

--

Yours sincerely,

Andrii Brylov, PMP, CSM

andrii.brylov@gmail.com | +1 901 438 4571 | Memphis, TN, US | Skype:
andrii.brylov | LinkedIn
<http://ua.linkedin.com/pub/andrii-brylov-pmp/7/272/183/>

2015-03-16 15:40 GMT-05:00 Krasimir Chariyski <notifications@github.com>:

**Comment by Chariyski** [comment]
Hi abrylov,

The image is not accessible, can you give a new link? 
About the smaller user stories, It is not hard to be done, but it is not a common use case and I prefer not to do it.

**Comment by abrylov** [comment]
Hey,

I attached image to the email. I appreciate your help :)

--

Yours sincerely,

Andrii Brylov, PMP, CSM

andrii.brylov@gmail.com | +1 901 438 4571 | Memphis, TN, US | Skype:
andrii.brylov | LinkedIn
<http://ua.linkedin.com/pub/andrii-brylov-pmp/7/272/183/>

2015-03-17 12:12 GMT-05:00 Krasimir Chariyski <notifications@github.com>:
