### ISSUE TITLE
Epic Info

### ISSUE THREAD

**Issue by StephenHarry** [Chariyski/JIRA-Cards-for-Task-Board#5]
I find your JIRA Cards extension really useful. Any chance you could reference the epic on the card? I would find this useful when discussing tasks as we don't always use versions.

many thanks
stephen

**Comment by Chariyski** [comment]
Hi,

I currently think to re-design the entire project and I'll have in mind your request.

**Comment by Chariyski** [comment]
Hi Stephen,

After some research it turned out that "epic" is using a Custom Field, therefor it can be different on any system depending on how many custom fields already existed. 

In short, I can not fulfill your request because of this restriction.

Best regards,
Krasimir
